# TTS Language Code Mappings
# Maps display names to provider-specific language codes (BCP-47 / ISO where applicable).

TTS_LANGUAGE_MAP = {
    "ElevenLabs": {
        "Hindi": "hi",
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Bengali": "bn",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Odia": "or",
        "Assamese": "as",
        "Urdu": "ur",
        "Nepali": "ne",
        "Sanskrit": "sa",
        "Bodo": "brx",
        "Dogri": "doi",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Santali": "sat",
        "Sindhi": "sd",
    },
    "Cartesia": {
        "Hindi": "hi",
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Bengali": "bn",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Odia": "or",
        "Assamese": "as",
        "Urdu": "ur",
        "Nepali": "ne",
        "Sanskrit": "sa",
        "Bodo": "brx",
        "Dogri": "doi",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Santali": "sat",
        "Sindhi": "sd",
    },
    "Google": {
        "Hindi": "hi-IN",
        "English": "en-US",
        "English (India)": "en-IN",
        "English (United States)": "en-US",
        "Bengali": "bn-IN",
        "Tamil": "ta-IN",
        "Telugu": "te-IN",
        "Gujarati": "gu-IN",
        "Kannada": "kn-IN",
        "Malayalam": "ml-IN",
        "Marathi": "mr-IN",
        "Punjabi": "pa-IN",
        "Odia": "or-IN",
        "Assamese": "as-IN",
        "Urdu": "ur-IN",
        "Nepali": "ne-NP",
        "Sanskrit": "sa-IN",
        "Bodo": "brx-IN",
        "Dogri": "doi-IN",
        "Konkani": "kok-IN",
        "Kashmiri": "ks-IN",
        "Maithili": "mai-IN",
        "Manipuri": "mni-IN",
        "Santali": "sat-IN",
        "Sindhi": "sd-IN",
    },
    "OpenAI": {
        "Hindi": "en",
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Bengali": "en",
        "Tamil": "en",
        "Telugu": "en",
        "Gujarati": "en",
        "Kannada": "en",
        "Malayalam": "en",
        "Marathi": "en",
        "Punjabi": "en",
        "Odia": "en",
        "Assamese": "en",
        "Urdu": "en",
        "Nepali": "en",
        "Sanskrit": "en",
        "Bodo": "en",
        "Dogri": "en",
        "Konkani": "en",
        "Kashmiri": "en",
        "Maithili": "en",
        "Manipuri": "en",
        "Santali": "en",
        "Sindhi": "en",
    },
    "Sarvam": {
        "Hindi": "hi-IN",
        "English": "en-IN",
        "English (India)": "en-IN",
        "English (United States)": "en-IN",
        "Bengali": "bn-IN",
        "Tamil": "ta-IN",
        "Telugu": "te-IN",
        "Gujarati": "gu-IN",
        "Kannada": "kn-IN",
        "Malayalam": "ml-IN",
        "Marathi": "mr-IN",
        "Punjabi": "pa-IN",
        "Odia": "od-IN",
        "Assamese": "as-IN",
        "Urdu": "ur-IN",
        "Nepali": "ne-IN",
        "Sanskrit": "sa-IN",
        "Bodo": "brx-IN",
        "Dogri": "doi-IN",
        "Konkani": "kok-IN",
        "Kashmiri": "ks-IN",
        "Maithili": "mai-IN",
        "Manipuri": "mni-IN",
        "Santali": "sat-IN",
        "Sindhi": "sd-IN",
    },
    "AI4Bharat": {
        "Hindi": "hi",
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Bengali": "bn",
        "bhb": "bhb",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Assamese": "as",
        "Odia": "or",
        "Urdu": "ur",
        "Nepali": "ne",
        "Sanskrit": "sa",
        "Bodo": "brx",
        "Dogri": "doi",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Santali": "sat",
        "Sindhi": "sd",
    },
    "Bhashini": {
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Hindi": "hi",
        "Bengali": "bn",
        "bhb": "bhb",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Assamese": "as",
        "Odia": "or",
        "Urdu": "ur",
        "Nepali": "ne",
        "Sanskrit": "sa",
        "Bodo": "brx",
        "Dogri": "doi",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Santali": "sat",
        "Sindhi": "sd",
    },
}


# Orpheus (AI4Bharat indic-orpheus-tts) speakers per language code, from the
# model-server voices-v2.json roster. The speaker name alone selects the
# language on the wire; English is spoken by the Hindi pair. First = default.
ORPHEUS_VOICES = {
    "as": ("Prastuti", "Ankur"),
    "bn": ("Ishita", "Sourav"),
    "bhb": ("Bhima", "Dhulji", "Govind", "Jhamku", "Kanku", "Sarju", "Tantya"),
    "brx": ("Gwrbw", "Sansuma"),
    "doi": ("Preeti", "Sham"),
    "en": ("Kavya", "Amit"),
    "gu": ("Dhara", "Parth"),
    "hi": ("Kavya", "Amit"),
    "kn": ("Deepika", "Adarsh"),
    "kok": ("Anjali", "Sandeep"),
    "ks": ("Zoon", "Ishfaq"),
    "mai": ("Vaidehi", "Madhukar"),
    "ml": ("Lakshmi", "Kiran"),
    "mni": ("Thoibi", "Chaoba"),
    "mr": ("Anagha", "Chinmay"),
    "ne": ("Srijana", "Sagar"),
    "or": ("Itishree", "Akash"),
    "pa": ("Kaur", "Manpreet"),
    "sa": ("Bharati", "Aryaman"),
    "sat": ("Phulmani", "Sibu"),
    "sd": ("Moomal", "Rano"),
    "ta": ("Anitha", "Arun"),
    "te": ("Sravani", "Vamsi"),
    "ur": ("Saba", "Zaid"),
}


def orpheus_voice(language_code: str, requested: str | None = None) -> str:
    """Return ``requested`` if it is a speaker of ``language_code``, else that language's default.

    Speaker names from other providers (e.g. Parler's "Divya") or another
    language would otherwise make Orpheus speak the wrong language or fail.
    """
    voices = ORPHEUS_VOICES.get(language_code) or ORPHEUS_VOICES["hi"]
    if requested:
        match = next((v for v in voices if v.lower() == requested.strip().lower()), None)
        if match:
            return match
    return voices[0]
